# в переменных: exit-коды, out/err потоки как 1/2, пустые аргументы для программы
set(SUCCESS 0)
set(USAGE 64)
set(DATA 65)
set(NO_INPUT 66)
set(IO_FAIL 74)
set(OUT 1)
set(ERR 2)
set(EMPTY_ARG "")
# для достижения io-fail
set(FOLDER_INPUT "${CMAKE_CURRENT_SOURCE_DIR}/input_data")

# === T1 C TESTS ====
# входные данные с ошибками
add_case(t1_c_empty t1_c "${EMPTY_ARG}" t1_nul "${NO_INPUT}" CONTAINS t1_nul "${ERR}")
add_case(t1_c_abc t1_c "${EMPTY_ARG}" t1_abc "${DATA}" CONTAINS t1_abc "${ERR}")
add_case(t1_c_float t1_c "${EMPTY_ARG}" t1_float "${DATA}" CONTAINS t1_float "${ERR}")
add_case(t1_c_high t1_c "${EMPTY_ARG}" t1_high "${USAGE}" CONTAINS t1_high "${ERR}")
add_case(t1_c_double_plus t1_c "${EMPTY_ARG}" t1_double_plus "${DATA}" CONTAINS t1_double_plus "${ERR}")
add_case(t1_c_plus_abc t1_c "${EMPTY_ARG}" t1_plus_abc "${DATA}" CONTAINS t1_plus_abc "${ERR}")
add_case(t1_c_plus_minus t1_c "${EMPTY_ARG}" t1_plus_minus "${DATA}" CONTAINS t1_plus_minus "${ERR}")
add_case(t1_c_plus_only t1_c "${EMPTY_ARG}" t1_plus_only "${DATA}" CONTAINS t1_plus_only "${ERR}")
add_case(t1_c_overflow t1_c "${EMPTY_ARG}" t1_overflow "${DATA}" CONTAINS t1_overflow "${ERR}")
add_case(t1_c_overflow_big t1_c "${EMPTY_ARG}" t1_overflow_big "${DATA}" CONTAINS t1_overflow_big "${ERR}")
add_case(t1_c_overflow_neg t1_c "${EMPTY_ARG}" t1_overflow_neg "${DATA}" CONTAINS t1_overflow_neg "${ERR}")
add_case(t1_c_int32_max t1_c "${EMPTY_ARG}" t1_int32_max "${USAGE}" CONTAINS t1_int32_max "${ERR}")
add_case(t1_c_hex t1_c "${EMPTY_ARG}" t1_hex "${DATA}" CONTAINS t1_hex "${ERR}")
# нормальные входные данные
add_case(t1_c_norm t1_c "${EMPTY_ARG}" t1_test1 "${SUCCESS}" EQ t1_test1 "${OUT}")
add_case(t1_c_plus t1_c "${EMPTY_ARG}" t1_plus "${SUCCESS}" EQ t1_test1 "${OUT}")
add_case(t1_c_leading_spaces t1_c "${EMPTY_ARG}" t1_leading_spaces "${SUCCESS}" EQ t1_test1 "${OUT}")
add_case(t1_c_space_plus t1_c "${EMPTY_ARG}" t1_space_plus "${SUCCESS}" EQ t1_test1 "${OUT}")
add_case(t1_c_leading_zero t1_c "${EMPTY_ARG}" t1_leading_zero "${SUCCESS}" EQ t1_leading_zero "${OUT}")


# === T1 CPP TESTS ====
# входные данные с ошибками
add_case(t1_cpp_empty t1_cpp "${EMPTY_ARG}" t1_nul "${NO_INPUT}" CONTAINS t1_nul "${ERR}")
add_case(t1_cpp_abc t1_cpp "${EMPTY_ARG}" t1_abc "${DATA}" CONTAINS t1_abc "${ERR}")
add_case(t1_cpp_float t1_cpp "${EMPTY_ARG}" t1_float "${DATA}" CONTAINS t1_float "${ERR}")
add_case(t1_cpp_high t1_cpp "${EMPTY_ARG}" t1_high "${USAGE}" CONTAINS t1_high "${ERR}")
add_case(t1_cpp_double_plus t1_cpp "${EMPTY_ARG}" t1_double_plus "${DATA}" CONTAINS t1_double_plus "${ERR}")
add_case(t1_cpp_plus_abc t1_cpp "${EMPTY_ARG}" t1_plus_abc "${DATA}" CONTAINS t1_plus_abc "${ERR}")
add_case(t1_cpp_plus_minus t1_cpp "${EMPTY_ARG}" t1_plus_minus "${DATA}" CONTAINS t1_plus_minus "${ERR}")
add_case(t1_cpp_plus_only t1_cpp "${EMPTY_ARG}" t1_plus_only "${DATA}" CONTAINS t1_plus_only "${ERR}")
add_case(t1_cpp_overflow t1_cpp "${EMPTY_ARG}" t1_overflow "${DATA}" CONTAINS t1_overflow "${ERR}")
add_case(t1_cpp_overflow_big t1_cpp "${EMPTY_ARG}" t1_overflow_big "${DATA}" CONTAINS t1_overflow_big "${ERR}")
add_case(t1_cpp_overflow_neg t1_cpp "${EMPTY_ARG}" t1_overflow_neg "${DATA}" CONTAINS t1_overflow_neg "${ERR}")
add_case(t1_cpp_int32_max t1_cpp "${EMPTY_ARG}" t1_int32_max "${USAGE}" CONTAINS t1_int32_max "${ERR}")
add_case(t1_cpp_hex t1_cpp "${EMPTY_ARG}" t1_hex "${DATA}" CONTAINS t1_hex "${ERR}")
# нормальные входные данные
add_case(t1_cpp_norm t1_cpp "${EMPTY_ARG}" t1_test1 "${SUCCESS}" EQ t1_test1 "${OUT}")
add_case(t1_cpp_plus t1_cpp "${EMPTY_ARG}" t1_plus "${SUCCESS}" EQ t1_test1 "${OUT}")
add_case(t1_cpp_leading_spaces t1_cpp "${EMPTY_ARG}" t1_leading_spaces "${SUCCESS}" EQ t1_test1 "${OUT}")
add_case(t1_cpp_space_plus t1_cpp "${EMPTY_ARG}" t1_space_plus "${SUCCESS}" EQ t1_test1 "${OUT}")
add_case(t1_cpp_leading_zero t1_cpp "${EMPTY_ARG}" t1_leading_zero "${SUCCESS}" EQ t1_leading_zero "${OUT}")

# === T2 C TESTS ===
# входные данные с ошибками
add_case(t2_c_eof_name t2_c "${EMPTY_ARG}" t2_eof_name "${NO_INPUT}" CONTAINS t2_eof_name "${ERR}")
add_case(t2_c_empty_name t2_c "${EMPTY_ARG}" t2_empty_name "${DATA}" CONTAINS t2_empty_name "${ERR}")
add_case(t2_c_eof_vertexes t2_c "${EMPTY_ARG}" t2_eof_vertexes "${NO_INPUT}" CONTAINS t2_eof_vertexes "${ERR}")
add_case(t2_c_empty_vertexes t2_c "${EMPTY_ARG}" t2_empty_vertexes "${DATA}" CONTAINS t2_empty_vertexes "${ERR}")
add_case(t2_c_fractional_vertexes t2_c "${EMPTY_ARG}" t2_fractional_vertexes "${DATA}" CONTAINS t2_fractional_vertexes "${ERR}")
add_case(t2_c_nan_vertexes t2_c "${EMPTY_ARG}" t2_nan_vertexes "${DATA}" CONTAINS t2_nan_vertexes "${ERR}")
add_case(t2_c_negative_vertexes t2_c "${EMPTY_ARG}" t2_negative_vertexes "${USAGE}" CONTAINS t2_negative_vertexes "${ERR}")
add_case(t2_c_double_plus t2_c "${EMPTY_ARG}" t2_double_plus "${DATA}" CONTAINS t2_double_plus "${ERR}")
add_case(t2_c_plus_abc t2_c "${EMPTY_ARG}" t2_plus_abc "${DATA}" CONTAINS t2_plus_abc "${ERR}")
add_case(t2_c_plus_minus t2_c "${EMPTY_ARG}" t2_plus_minus "${DATA}" CONTAINS t2_plus_minus "${ERR}")
add_case(t2_c_plus_only t2_c "${EMPTY_ARG}" t2_plus_only "${DATA}" CONTAINS t2_plus_only "${ERR}")
add_case(t2_c_overflow t2_c "${EMPTY_ARG}" t2_overflow "${DATA}" CONTAINS t2_overflow "${ERR}")
add_case(t2_c_overflow_big t2_c "${EMPTY_ARG}" t2_overflow_big "${DATA}" CONTAINS t2_overflow_big "${ERR}")
add_case(t2_c_overflow_neg t2_c "${EMPTY_ARG}" t2_overflow_neg "${DATA}" CONTAINS t2_overflow_neg "${ERR}")
add_case(t2_c_hex t2_c "${EMPTY_ARG}" t2_hex "${DATA}" CONTAINS t2_hex "${ERR}")
# нормальные входные данные
add_case(t2_c_norm t2_c "${EMPTY_ARG}" t2_input "${SUCCESS}" EQ t2_norm "${OUT}")
add_case(t2_c_plus t2_c "${EMPTY_ARG}" t2_plus "${SUCCESS}" EQ t2_norm "${OUT}")
add_case(t2_c_leading_spaces t2_c "${EMPTY_ARG}" t2_leading_spaces "${SUCCESS}" EQ t2_norm "${OUT}")
add_case(t2_c_space_plus t2_c "${EMPTY_ARG}" t2_space_plus "${SUCCESS}" EQ t2_norm "${OUT}")
add_case(t2_c_leading_zero t2_c "${EMPTY_ARG}" t2_leading_zero "${SUCCESS}" EQ t2_leading_zero "${OUT}")

# === T2 CPP TESTS ===
# входные данные с ошибками
add_case(t2_cpp_eof_name t2_cpp "${EMPTY_ARG}" t2_eof_name "${NO_INPUT}" CONTAINS t2_eof_name "${ERR}")
add_case(t2_cpp_empty_name t2_cpp "${EMPTY_ARG}" t2_empty_name "${DATA}" CONTAINS t2_empty_name "${ERR}")
add_case(t2_cpp_eof_vertexes t2_cpp "${EMPTY_ARG}" t2_eof_vertexes "${NO_INPUT}" CONTAINS t2_eof_vertexes "${ERR}")
add_case(t2_cpp_empty_vertexes t2_cpp "${EMPTY_ARG}" t2_empty_vertexes "${DATA}" CONTAINS t2_empty_vertexes "${ERR}")
add_case(t2_cpp_fractional_vertexes t2_cpp "${EMPTY_ARG}" t2_fractional_vertexes "${DATA}" CONTAINS t2_fractional_vertexes "${ERR}")
add_case(t2_cpp_nan_vertexes t2_cpp "${EMPTY_ARG}" t2_nan_vertexes "${DATA}" CONTAINS t2_nan_vertexes "${ERR}")
add_case(t2_cpp_negative_vertexes t2_cpp "${EMPTY_ARG}" t2_negative_vertexes "${USAGE}" CONTAINS t2_negative_vertexes "${ERR}")
add_case(t2_cpp_double_plus t2_cpp "${EMPTY_ARG}" t2_double_plus "${DATA}" CONTAINS t2_double_plus "${ERR}")
add_case(t2_cpp_plus_abc t2_cpp "${EMPTY_ARG}" t2_plus_abc "${DATA}" CONTAINS t2_plus_abc "${ERR}")
add_case(t2_cpp_plus_minus t2_cpp "${EMPTY_ARG}" t2_plus_minus "${DATA}" CONTAINS t2_plus_minus "${ERR}")
add_case(t2_cpp_plus_only t2_cpp "${EMPTY_ARG}" t2_plus_only "${DATA}" CONTAINS t2_plus_only "${ERR}")
add_case(t2_cpp_overflow t2_cpp "${EMPTY_ARG}" t2_overflow "${DATA}" CONTAINS t2_overflow "${ERR}")
add_case(t2_cpp_overflow_big t2_cpp "${EMPTY_ARG}" t2_overflow_big "${DATA}" CONTAINS t2_overflow_big "${ERR}")
add_case(t2_cpp_overflow_neg t2_cpp "${EMPTY_ARG}" t2_overflow_neg "${DATA}" CONTAINS t2_overflow_neg "${ERR}")
add_case(t2_cpp_hex t2_cpp "${EMPTY_ARG}" t2_hex "${DATA}" CONTAINS t2_hex "${ERR}")
# нормальные входные данные
add_case(t2_cpp_norm t2_cpp "${EMPTY_ARG}" t2_input "${SUCCESS}" EQ t2_norm "${OUT}")
add_case(t2_cpp_plus t2_cpp "${EMPTY_ARG}" t2_plus "${SUCCESS}" EQ t2_norm "${OUT}")
add_case(t2_cpp_leading_spaces t2_cpp "${EMPTY_ARG}" t2_leading_spaces "${SUCCESS}" EQ t2_norm "${OUT}")
add_case(t2_cpp_space_plus t2_cpp "${EMPTY_ARG}" t2_space_plus "${SUCCESS}" EQ t2_norm "${OUT}")
add_case(t2_cpp_leading_zero t2_cpp "${EMPTY_ARG}" t2_leading_zero "${SUCCESS}" EQ t2_leading_zero "${OUT}")

# === T3 C TESTS ===
# тест на io-fail - только под UNIX
if(UNIX)
  add_case(t3_c_io t3_c "${EMPTY_ARG}" "${FOLDER_INPUT}" "${IO_FAIL}" CONTAINS t3_t4_io_fail "${ERR}")
endif()
# входные данные с ошибками
add_case(t3_c_empty t3_c "${EMPTY_ARG}" t3_empty_case "${NO_INPUT}" CONTAINS t3_empty_case "${ERR}")
add_case(t3_c_not_digit_case t3_c "${EMPTY_ARG}" t3_not_digit_case "${DATA}" CONTAINS t3_not_digit_case "${ERR}")
add_case(t3_c_too_few_args_case t3_c "${EMPTY_ARG}" t3_too_few_args_case "${DATA}" CONTAINS t3_too_few_args_case "${ERR}")
add_case(t3_c_too_much_args_case t3_c "${EMPTY_ARG}" t3_too_much_args_case "${DATA}" CONTAINS t3_too_much_args_case "${ERR}")
add_case(t3_c_extra_nan t3_c "${EMPTY_ARG}" t3_extra_nan "${DATA}" CONTAINS t3_extra_nan "${ERR}")
add_case(t3_c_x_y_z_4k t3_c "${EMPTY_ARG}" t3_x_y_z_4k "${DATA}" CONTAINS t3_x_y_z_4k "${ERR}")
add_case(t3_c_inf_coord t3_c "${EMPTY_ARG}" t3_inf_coord "${DATA}" CONTAINS t3_inf_coord "${ERR}")
add_case(t3_c_x_ky_z t3_c "${EMPTY_ARG}" t3_x_ky_z "${DATA}" CONTAINS t3_x_ky_z "${ERR}")
add_case(t3_c_x_yk_z t3_c "${EMPTY_ARG}" t3_x_yk_z "${DATA}" CONTAINS t3_x_yk_z "${ERR}")
add_case(t3_c_double_plus t3_c "${EMPTY_ARG}" t3_double_plus "${DATA}" CONTAINS t3_double_plus "${ERR}")
add_case(t3_c_plus_abc t3_c "${EMPTY_ARG}" t3_plus_abc "${DATA}" CONTAINS t3_plus_abc "${ERR}")
add_case(t3_c_plus_minus_coord t3_c "${EMPTY_ARG}" t3_t4_plus_minus_coord "${DATA}" CONTAINS t3_t4_plus_minus_coord "${ERR}")
add_case(t3_c_plus_minus_extra t3_c "${EMPTY_ARG}" t3_t4_plus_minus_extra "${DATA}" CONTAINS t3_t4_plus_minus_extra "${ERR}")
# нормальные входные данные
add_case(t3_c_test1 t3_c "${EMPTY_ARG}" t3_test1 "${SUCCESS}" EQ t3_test1 "${OUT}")
add_case(t3_c_test2 t3_c "${EMPTY_ARG}" t3_test2 "${SUCCESS}" EQ t3_test2 "${OUT}") 
add_case(t3_c_test3 t3_c "${EMPTY_ARG}" t3_test3 "${SUCCESS}" EQ t3_test3 "${OUT}")
add_case(t3_c_scientific t3_c "${EMPTY_ARG}" t3_scientific "${SUCCESS}" EQ t3_scientific "${OUT}")
# (hex / overflow / подформа записи)
add_case(t3_c_hex_coord t3_c "${EMPTY_ARG}" t3_hex_coord "${DATA}" CONTAINS t3_hex_coord "${ERR}")
add_case(t3_c_hex_coord_upper t3_c "${EMPTY_ARG}" t3_hex_coord_upper "${DATA}" CONTAINS t3_hex_coord_upper "${ERR}")
add_case(t3_c_hex_extra_coord t3_c "${EMPTY_ARG}" t3_hex_extra_coord "${DATA}" CONTAINS t3_hex_extra_coord "${ERR}")
add_case(t3_c_overflow_coord t3_c "${EMPTY_ARG}" t3_overflow_coord "${DATA}" CONTAINS t3_overflow_coord "${ERR}")
add_case(t3_c_underflow_coord t3_c "${EMPTY_ARG}" t3_underflow_coord "${DATA}" CONTAINS t3_underflow_coord "${ERR}")
add_case(t3_c_subnormal_coord t3_c "${EMPTY_ARG}" t3_subnormal_coord "${SUCCESS}" EQ t3_subnormal_coord "${OUT}")
# вывод совпадает с t3_test1: та же точка (1.5, 2.5, 3.5), отличается только ведущий пробел во входе
add_case(t3_c_leading_spaces t3_c "${EMPTY_ARG}" t3_leading_spaces "${SUCCESS}" EQ t3_test1 "${OUT}")
add_case(t3_c_exp_plus t3_c "${EMPTY_ARG}" t3_exp_plus "${SUCCESS}" EQ t3_exp_plus "${OUT}")
add_case(t3_c_exp_upper t3_c "${EMPTY_ARG}" t3_exp_upper "${SUCCESS}" EQ t3_exp_upper "${OUT}")
add_case(t3_c_exp_negative t3_c "${EMPTY_ARG}" t3_exp_negative "${SUCCESS}" EQ t3_exp_negative "${OUT}")
add_case(t3_c_infinity_coord t3_c "${EMPTY_ARG}" t3_infinity_coord "${DATA}" CONTAINS t3_infinity_coord "${ERR}")
add_case(t3_c_nan_payload_coord t3_c "${EMPTY_ARG}" t3_nan_payload_coord "${DATA}" CONTAINS t3_nan_payload_coord "${ERR}")
add_case(t3_c_comma_coord t3_c "${EMPTY_ARG}" t3_comma_coord "${DATA}" CONTAINS t3_comma_coord "${ERR}")
add_case(t3_c_dot_trailing_coord t3_c "${EMPTY_ARG}" t3_dot_trailing_coord "${SUCCESS}" EQ t3_dot_trailing_coord "${OUT}")
add_case(t3_c_dot_leading_coord t3_c "${EMPTY_ARG}" t3_dot_leading_coord "${SUCCESS}" EQ t3_dot_leading_coord "${OUT}")


# === T3 CPP TESTS ===
# тест на io-fail - только под UNIX
if(UNIX)
  add_case(t3_cpp_io t3_cpp "${EMPTY_ARG}" "${FOLDER_INPUT}" "${IO_FAIL}" CONTAINS t3_t4_io_fail "${ERR}")
endif()
# входные данные с ошибками
add_case(t3_cpp_empty t3_cpp "${EMPTY_ARG}" t3_empty_case "${NO_INPUT}" CONTAINS t3_empty_case "${ERR}")
add_case(t3_cpp_not_digit_case t3_cpp "${EMPTY_ARG}" t3_not_digit_case "${DATA}" CONTAINS t3_not_digit_case "${ERR}")
add_case(t3_cpp_too_few_args_case t3_cpp "${EMPTY_ARG}" t3_too_few_args_case "${DATA}" CONTAINS t3_too_few_args_case "${ERR}")
add_case(t3_cpp_too_much_args_case t3_cpp "${EMPTY_ARG}" t3_too_much_args_case "${DATA}" CONTAINS t3_too_much_args_case "${ERR}")
add_case(t3_cpp_extra_nan t3_cpp "${EMPTY_ARG}" t3_extra_nan "${DATA}" CONTAINS t3_extra_nan "${ERR}")
add_case(t3_cpp_x_y_z_4k t3_cpp "${EMPTY_ARG}" t3_x_y_z_4k "${DATA}" CONTAINS t3_x_y_z_4k "${ERR}")
add_case(t3_cpp_inf_coord t3_cpp "${EMPTY_ARG}" t3_inf_coord "${DATA}" CONTAINS t3_inf_coord "${ERR}")
add_case(t3_cpp_x_ky_z t3_cpp "${EMPTY_ARG}" t3_x_ky_z "${DATA}" CONTAINS t3_x_ky_z "${ERR}")
add_case(t3_cpp_x_yk_z t3_cpp "${EMPTY_ARG}" t3_x_yk_z "${DATA}" CONTAINS t3_x_yk_z "${ERR}")
add_case(t3_cpp_double_plus t3_cpp "${EMPTY_ARG}" t3_double_plus "${DATA}" CONTAINS t3_double_plus "${ERR}")
add_case(t3_cpp_plus_abc t3_cpp "${EMPTY_ARG}" t3_plus_abc "${DATA}" CONTAINS t3_plus_abc "${ERR}")
add_case(t3_cpp_plus_minus_coord t3_cpp "${EMPTY_ARG}" t3_t4_plus_minus_coord "${DATA}" CONTAINS t3_t4_plus_minus_coord "${ERR}")
add_case(t3_cpp_plus_minus_extra t3_cpp "${EMPTY_ARG}" t3_t4_plus_minus_extra "${DATA}" CONTAINS t3_t4_plus_minus_extra "${ERR}")
# нормальные входные данные
add_case(t3_cpp_test1 t3_cpp "${EMPTY_ARG}" t3_test1 "${SUCCESS}" EQ t3_test1 "${OUT}")
add_case(t3_cpp_test2 t3_cpp "${EMPTY_ARG}" t3_test2 "${SUCCESS}" EQ t3_test2 "${OUT}") 
add_case(t3_cpp_test3 t3_cpp "${EMPTY_ARG}" t3_test3 "${SUCCESS}" EQ t3_test3 "${OUT}")
add_case(t3_cpp_scientific t3_cpp "${EMPTY_ARG}" t3_scientific "${SUCCESS}" EQ t3_scientific "${OUT}")
# hex / overflow / подформа записи
add_case(t3_cpp_hex_coord t3_cpp "${EMPTY_ARG}" t3_hex_coord "${DATA}" CONTAINS t3_hex_coord "${ERR}")
add_case(t3_cpp_hex_coord_upper t3_cpp "${EMPTY_ARG}" t3_hex_coord_upper "${DATA}" CONTAINS t3_hex_coord_upper "${ERR}")
add_case(t3_cpp_hex_extra_coord t3_cpp "${EMPTY_ARG}" t3_hex_extra_coord "${DATA}" CONTAINS t3_hex_extra_coord "${ERR}")
add_case(t3_cpp_overflow_coord t3_cpp "${EMPTY_ARG}" t3_overflow_coord "${DATA}" CONTAINS t3_overflow_coord "${ERR}")
add_case(t3_cpp_underflow_coord t3_cpp "${EMPTY_ARG}" t3_underflow_coord "${DATA}" CONTAINS t3_underflow_coord "${ERR}")
add_case(t3_cpp_subnormal_coord t3_cpp "${EMPTY_ARG}" t3_subnormal_coord "${SUCCESS}" EQ t3_subnormal_coord "${OUT}")
# вывод совпадает с t3_test1: та же точка (1.5, 2.5, 3.5), отличается только ведущий пробел во входе
add_case(t3_cpp_leading_spaces t3_cpp "${EMPTY_ARG}" t3_leading_spaces "${SUCCESS}" EQ t3_test1 "${OUT}")
add_case(t3_cpp_exp_plus t3_cpp "${EMPTY_ARG}" t3_exp_plus "${SUCCESS}" EQ t3_exp_plus "${OUT}")
add_case(t3_cpp_exp_upper t3_cpp "${EMPTY_ARG}" t3_exp_upper "${SUCCESS}" EQ t3_exp_upper "${OUT}")
add_case(t3_cpp_exp_negative t3_cpp "${EMPTY_ARG}" t3_exp_negative "${SUCCESS}" EQ t3_exp_negative "${OUT}")
add_case(t3_cpp_infinity_coord t3_cpp "${EMPTY_ARG}" t3_infinity_coord "${DATA}" CONTAINS t3_infinity_coord "${ERR}")
add_case(t3_cpp_nan_payload_coord t3_cpp "${EMPTY_ARG}" t3_nan_payload_coord "${DATA}" CONTAINS t3_nan_payload_coord "${ERR}")
add_case(t3_cpp_comma_coord t3_cpp "${EMPTY_ARG}" t3_comma_coord "${DATA}" CONTAINS t3_comma_coord "${ERR}")
add_case(t3_cpp_dot_trailing_coord t3_cpp "${EMPTY_ARG}" t3_dot_trailing_coord "${SUCCESS}" EQ t3_dot_trailing_coord "${OUT}")
add_case(t3_cpp_dot_leading_coord t3_cpp "${EMPTY_ARG}" t3_dot_leading_coord "${SUCCESS}" EQ t3_dot_leading_coord "${OUT}")

# === РАДИУСЫ ===
set(RAD_TOO_MUCH 2 3)
set(RAD_SYMB 4ch)
set(RAD_INF inf)
set(RAD_NEG -10)
set(RAD_PLUS_PLUS ++10)
set(RAD_PLUS_ABC +abc)
set(RAD_PLUS_MINUS +-3)
set(RAD_POSITIVE +10)
set(RAD1 1)
set(RAD5 5)
set(RAD8 8)
set(RAD10 10)
set(RAD100 100)
set(RAD_HEX 0x10)
set(RAD_HEX_UPPER 0X10)
set(RAD_OVERFLOW 1e400)
set(RAD_UNDERFLOW 1e-400)
# для координат с большим модулем (exp_plus=300, exp_upper=100)
set(RAD400 400)
# радиусы с пробелами в начале
set(RAD_SPACE "   10")
set(RAD_SPACE_HEX "   0x10")
set(RAD_SPACE_PLUS "   +10")
# с пробелом в конце 
set(RAD_SPACE_END "10   ")
# пустой радиус: строка только из пробелов (после обрезки — пусто)
set(RAD_SPACES [=[   ]=])
# радиус — одна строка с пробелом внутри: не число
set(RAD_INNER_SPACE [=[2 3]=])
# радиус — одна строка с пробелом и кавычкой внутри: не число
set(RAD_INNER_QUOTE [=[2" 3]=])
# радиус — строка с хвостовым обратным слешем: не число
set(RAD_TRAILING_BACKSLASH [=[10\]=])
# радиус — строка с несколькими кавычками: не число
set(RAD_MULTI_QUOTE [=[2"3"]=])

# === T4 C TESTS ===
# тест на io-fail - только под UNIX
if(UNIX)
  add_case(t4_c_io t4_c "${RAD1}" "${FOLDER_INPUT}" "${IO_FAIL}" CONTAINS t3_t4_io_fail "${ERR}")
endif()
# плохие значения радиуса
# t4_bad_radius - для наличия потока input, сам по себе не имеет значения
add_case(t4_c_radius_empty t4_c "${EMPTY_ARG}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_empty "${ERR}")
add_case(t4_c_radius_too_much t4_c "${RAD_TOO_MUCH}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_too_much "${ERR}")
add_case(t4_c_radius_symbol t4_c "${RAD_SYMB}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_symbol "${ERR}")
add_case(t4_c_radius_inf t4_c "${RAD_INF}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_inf "${ERR}")
add_case(t4_c_radius_negative t4_c "${RAD_NEG}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_negative "${ERR}")
add_case(t4_c_radius_plus_plus t4_c "${RAD_PLUS_PLUS}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_plus_plus "${ERR}")
add_case(t4_c_radius_plus_abc t4_c "${RAD_PLUS_ABC}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_plus_abc "${ERR}")
add_case(t4_c_radius_plus_minus t4_c "${RAD_PLUS_MINUS}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_plus_minus "${ERR}")
add_case(t4_c_radius_hex t4_c "${RAD_HEX}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_hex "${ERR}")
add_case(t4_c_radius_hex_upper t4_c "${RAD_HEX_UPPER}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_hex_upper "${ERR}")
add_case(t4_c_radius_overflow t4_c "${RAD_OVERFLOW}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_overflow "${ERR}")
add_case(t4_c_radius_underflow t4_c "${RAD_UNDERFLOW}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_underflow "${ERR}")
add_case(t4_c_rad_space_hex t4_c "${RAD_SPACE_HEX}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_space_hex "${ERR}")
add_case(t4_c_radius_spaces t4_c "${RAD_SPACES}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_spaces "${ERR}")
add_case(t4_c_radius_inner_space t4_c "${RAD_INNER_SPACE}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_inner_space "${ERR}")
add_case(t4_c_radius_inner_quote t4_c "${RAD_INNER_QUOTE}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_inner_quote "${ERR}")
add_case(t4_c_radius_trailing_backslash t4_c "${RAD_TRAILING_BACKSLASH}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_trailing_backslash "${ERR}")
add_case(t4_c_radius_multi_quote t4_c "${RAD_MULTI_QUOTE}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_multi_quote "${ERR}")

# плохие точки
add_case(t4_c_symbol_coords t4_c "${RAD1}" t4_symbol_coords "${DATA}" CONTAINS t4_symbol_coords "${ERR}")
add_case(t4_c_too_few_coords t4_c "${RAD1}" t4_too_few_coords "${DATA}" CONTAINS t4_too_few_coords "${ERR}")
add_case(t4_c_empty_coords t4_c "${RAD1}" t4_empty_coords "${NO_INPUT}" CONTAINS t4_empty_coords "${ERR}")
add_case(t4_c_too_much_coords t4_c "${RAD1}" t4_too_much_coords "${DATA}" CONTAINS t4_too_much_coords "${ERR}")
add_case(t4_c_extra_nan t4_c "${RAD1}" t4_extra_nan "${DATA}" CONTAINS t4_extra_nan "${ERR}")
add_case(t4_c_x_y_z_4k t4_c "${RAD1}" t4_x_y_z_4k "${DATA}" CONTAINS t4_x_y_z_4k "${ERR}")
add_case(t4_c_x_y_z_k4 t4_c "${RAD1}" t4_x_y_z_k4 "${DATA}" CONTAINS t4_x_y_z_k4 "${ERR}")
add_case(t4_c_inf_coord t4_c "${RAD1}" t4_inf_coord "${DATA}" CONTAINS t4_inf_coord "${ERR}")
add_case(t4_c_x_ky_z t4_c "${RAD1}" t4_x_ky_z "${DATA}" CONTAINS t4_x_ky_z "${ERR}")
add_case(t4_c_x_yk_z t4_c "${RAD1}" t4_x_yk_z "${DATA}" CONTAINS t4_x_yk_z "${ERR}")
add_case(t4_c_plus_plus_coord t4_c "${RAD1}" t4_plus_plus_coord "${DATA}" CONTAINS t4_plus_plus_coord "${ERR}")
add_case(t4_c_plus_abc_coord t4_c "${RAD1}" t4_plus_abc_coord "${DATA}" CONTAINS t4_plus_abc_coord "${ERR}")
add_case(t4_c_plus_minus_coord t4_c "${RAD1}" t3_t4_plus_minus_coord "${DATA}" CONTAINS t3_t4_plus_minus_coord "${ERR}")
add_case(t4_c_plus_minus_extra t4_c "${RAD1}" t3_t4_plus_minus_extra "${DATA}" CONTAINS t3_t4_plus_minus_extra "${ERR}")
# нормальные данные
# единственная точка и она проходит
add_case(t4_c_test1 t4_c "${RAD8}" t4_test1 "${SUCCESS}" EQ t4_test1 "${OUT}")
# много точек и только одна проходит
add_case(t4_c_test2 t4_c "${RAD10}" t4_test2 "${SUCCESS}" EQ t4_test2 "${OUT}")
# как прошлый тест, но радиус со знаком "+". результат и поведение должны совпасть
add_case(t4_c_plus t4_c "${RAD_POSITIVE}" t4_test2 "${SUCCESS}" EQ t4_test2 "${OUT}")
# как прошлый тест, но радиус с пробелами в начале. результат и поведение должны совпасть
add_case(t4_c_rad_leading_space t4_c "${RAD_SPACE}" t4_test2 "${SUCCESS}" EQ t4_test2 "${OUT}")
# как прошлый тест, но радиус с пробелами в конце. результат и поведение должны совпасть
add_case(t4_c_rad_space_end t4_c "${RAD_SPACE_END}" t4_test2 "${SUCCESS}" EQ t4_test2 "${OUT}")
# одна точка, но она не проходит
add_case(t4_c_test3 t4_c "${RAD5}" t4_test3 "${SUCCESS}" EQ t4_test3 "${OUT}")
# входные данные с минусом и экспонентой 
add_case(t4_c_scientific t4_c "${RAD100}" t4_scientific "${SUCCESS}" EQ t4_scientific "${OUT}")
# пробелы + знак "+": успех, радиус 10 - результат как в t4_test2
add_case(t4_c_rad_space_plus t4_c "${RAD_SPACE_PLUS}" t4_test2 "${SUCCESS}" EQ t4_test2 "${OUT}")
# (hex / overflow / подформа записи)
add_case(t4_c_hex_coord t4_c "${RAD1}" t4_hex_coord "${DATA}" CONTAINS t4_hex_coord "${ERR}")
add_case(t4_c_hex_coord_upper t4_c "${RAD1}" t4_hex_coord_upper "${DATA}" CONTAINS t4_hex_coord_upper "${ERR}")
add_case(t4_c_hex_extra_coord t4_c "${RAD1}" t4_hex_extra_coord "${DATA}" CONTAINS t4_hex_extra_coord "${ERR}")
add_case(t4_c_overflow_coord t4_c "${RAD1}" t4_overflow_coord "${DATA}" CONTAINS t4_overflow_coord "${ERR}")
add_case(t4_c_underflow_coord t4_c "${RAD1}" t4_underflow_coord "${DATA}" CONTAINS t4_underflow_coord "${ERR}")
add_case(t4_c_subnormal_coord t4_c "${RAD1}" t4_subnormal_coord "${SUCCESS}" EQ t4_subnormal_coord "${OUT}")
add_case(t4_c_leading_spaces t4_c "${RAD5}" t4_leading_spaces "${SUCCESS}" EQ t4_leading_spaces "${OUT}")
add_case(t4_c_exp_plus t4_c "${RAD400}" t4_exp_plus "${SUCCESS}" EQ t4_exp_plus "${OUT}")
add_case(t4_c_exp_upper t4_c "${RAD400}" t4_exp_upper "${SUCCESS}" EQ t4_exp_upper "${OUT}")
add_case(t4_c_exp_negative t4_c "${RAD1}" t4_exp_negative "${SUCCESS}" EQ t4_exp_negative "${OUT}")
add_case(t4_c_infinity_coord t4_c "${RAD1}" t4_infinity_coord "${DATA}" CONTAINS t4_infinity_coord "${ERR}")
add_case(t4_c_nan_payload_coord t4_c "${RAD1}" t4_nan_payload_coord "${DATA}" CONTAINS t4_nan_payload_coord "${ERR}")
add_case(t4_c_comma_coord t4_c "${RAD1}" t4_comma_coord "${DATA}" CONTAINS t4_comma_coord "${ERR}")
add_case(t4_c_dot_trailing_coord t4_c "${RAD8}" t4_dot_trailing_coord "${SUCCESS}" EQ t4_dot_trailing_coord "${OUT}")
add_case(t4_c_dot_leading_coord t4_c "${RAD5}" t4_dot_leading_coord "${SUCCESS}" EQ t4_dot_leading_coord "${OUT}")

# === T4 CPP TESTS ===
# тест на io-fail - только под UNIX
if(UNIX)
  add_case(t4_cpp_io t4_cpp "${RAD1}" "${FOLDER_INPUT}" "${IO_FAIL}" CONTAINS t3_t4_io_fail "${ERR}")
endif()
# плохие значения радиуса
add_case(t4_cpp_radius_empty t4_cpp "${EMPTY_ARG}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_empty "${ERR}")
add_case(t4_cpp_radius_too_much t4_cpp "${RAD_TOO_MUCH}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_too_much "${ERR}")
add_case(t4_cpp_radius_symbol t4_cpp "${RAD_SYMB}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_symbol "${ERR}")
add_case(t4_cpp_radius_inf t4_cpp "${RAD_INF}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_inf "${ERR}")
add_case(t4_cpp_radius_negative t4_cpp "${RAD_NEG}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_negative "${ERR}")
add_case(t4_cpp_radius_plus_plus t4_cpp "${RAD_PLUS_PLUS}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_plus_plus "${ERR}")
add_case(t4_cpp_radius_plus_abc t4_cpp "${RAD_PLUS_ABC}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_plus_abc "${ERR}")
add_case(t4_cpp_radius_plus_minus t4_cpp "${RAD_PLUS_MINUS}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_plus_minus "${ERR}")
add_case(t4_cpp_radius_hex t4_cpp "${RAD_HEX}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_hex "${ERR}")
add_case(t4_cpp_radius_hex_upper t4_cpp "${RAD_HEX_UPPER}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_hex_upper "${ERR}")
add_case(t4_cpp_radius_overflow t4_cpp "${RAD_OVERFLOW}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_overflow "${ERR}")
add_case(t4_cpp_radius_underflow t4_cpp "${RAD_UNDERFLOW}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_underflow "${ERR}")
add_case(t4_cpp_rad_space_hex t4_cpp "${RAD_SPACE_HEX}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_space_hex "${ERR}")
add_case(t4_cpp_radius_spaces t4_cpp "${RAD_SPACES}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_spaces "${ERR}")
add_case(t4_cpp_radius_inner_space t4_cpp "${RAD_INNER_SPACE}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_inner_space "${ERR}")
add_case(t4_cpp_radius_inner_quote t4_cpp "${RAD_INNER_QUOTE}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_inner_quote "${ERR}")
add_case(t4_cpp_radius_trailing_backslash t4_cpp "${RAD_TRAILING_BACKSLASH}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_trailing_backslash "${ERR}")
add_case(t4_cpp_radius_multi_quote t4_cpp "${RAD_MULTI_QUOTE}" t4_bad_radius "${USAGE}" CONTAINS t4_radius_multi_quote "${ERR}")

# плохие точки
add_case(t4_cpp_symbol_coords t4_cpp "${RAD1}" t4_symbol_coords "${DATA}" CONTAINS t4_symbol_coords "${ERR}")
add_case(t4_cpp_too_few_coords t4_cpp "${RAD1}" t4_too_few_coords "${DATA}" CONTAINS t4_too_few_coords "${ERR}")
add_case(t4_cpp_empty_coords t4_cpp "${RAD1}" t4_empty_coords "${NO_INPUT}" CONTAINS t4_empty_coords "${ERR}")
add_case(t4_cpp_too_much_coords t4_cpp "${RAD1}" t4_too_much_coords "${DATA}" CONTAINS t4_too_much_coords "${ERR}")
add_case(t4_cpp_extra_nan t4_cpp "${RAD1}" t4_extra_nan "${DATA}" CONTAINS t4_extra_nan "${ERR}")
add_case(t4_cpp_x_y_z_4k t4_cpp "${RAD1}" t4_x_y_z_4k "${DATA}" CONTAINS t4_x_y_z_4k "${ERR}")
add_case(t4_cpp_x_y_z_k4 t4_cpp "${RAD1}" t4_x_y_z_k4 "${DATA}" CONTAINS t4_x_y_z_k4 "${ERR}")
add_case(t4_cpp_inf_coord t4_cpp "${RAD1}" t4_inf_coord "${DATA}" CONTAINS t4_inf_coord "${ERR}")
add_case(t4_cpp_x_ky_z t4_cpp "${RAD1}" t4_x_ky_z "${DATA}" CONTAINS t4_x_ky_z "${ERR}")
add_case(t4_cpp_x_yk_z t4_cpp "${RAD1}" t4_x_yk_z "${DATA}" CONTAINS t4_x_yk_z "${ERR}")
add_case(t4_cpp_plus_plus_coord t4_cpp "${RAD1}" t4_plus_plus_coord "${DATA}" CONTAINS t4_plus_plus_coord "${ERR}")
add_case(t4_cpp_plus_abc_coord t4_cpp "${RAD1}" t4_plus_abc_coord "${DATA}" CONTAINS t4_plus_abc_coord "${ERR}")
add_case(t4_cpp_plus_minus_coord t4_cpp "${RAD1}" t3_t4_plus_minus_coord "${DATA}" CONTAINS t3_t4_plus_minus_coord "${ERR}")
add_case(t4_cpp_plus_minus_extra t4_cpp "${RAD1}" t3_t4_plus_minus_extra "${DATA}" CONTAINS t3_t4_plus_minus_extra "${ERR}")
# нормальные данные
add_case(t4_cpp_test1 t4_cpp "${RAD8}" t4_test1 "${SUCCESS}" EQ t4_test1 "${OUT}")
add_case(t4_cpp_test2 t4_cpp "${RAD10}" t4_test2 "${SUCCESS}" EQ t4_test2 "${OUT}")
# как прошлый тест, но радиус со знаком "+". результат и поведение должны совпасть
add_case(t4_cpp_plus t4_cpp "${RAD_POSITIVE}" t4_test2 "${SUCCESS}" EQ t4_test2 "${OUT}")
# как прошлый тест, но радиус с пробелами в начале. результат и поведение должны совпасть
add_case(t4_cpp_rad_leading_space t4_cpp "${RAD_SPACE}" t4_test2 "${SUCCESS}" EQ t4_test2 "${OUT}")
# как прошлый тест, но радиус с пробелами в конце. результат и поведение должны совпасть
add_case(t4_cpp_rad_space_end t4_cpp "${RAD_SPACE_END}" t4_test2 "${SUCCESS}" EQ t4_test2 "${OUT}")
add_case(t4_cpp_test3 t4_cpp "${RAD5}" t4_test3 "${SUCCESS}" EQ t4_test3 "${OUT}")
add_case(t4_cpp_scientific t4_cpp "${RAD100}" t4_scientific "${SUCCESS}" EQ t4_scientific "${OUT}")
# пробелы + знак "+": успех, радиус 10 - результат как в t4_test2
add_case(t4_cpp_rad_space_plus t4_cpp "${RAD_SPACE_PLUS}" t4_test2 "${SUCCESS}" EQ t4_test2 "${OUT}")
# (hex / overflow / подформа записи)
add_case(t4_cpp_hex_coord t4_cpp "${RAD1}" t4_hex_coord "${DATA}" CONTAINS t4_hex_coord "${ERR}")
add_case(t4_cpp_hex_coord_upper t4_cpp "${RAD1}" t4_hex_coord_upper "${DATA}" CONTAINS t4_hex_coord_upper "${ERR}")
add_case(t4_cpp_hex_extra_coord t4_cpp "${RAD1}" t4_hex_extra_coord "${DATA}" CONTAINS t4_hex_extra_coord "${ERR}")
add_case(t4_cpp_overflow_coord t4_cpp "${RAD1}" t4_overflow_coord "${DATA}" CONTAINS t4_overflow_coord "${ERR}")
add_case(t4_cpp_underflow_coord t4_cpp "${RAD1}" t4_underflow_coord "${DATA}" CONTAINS t4_underflow_coord "${ERR}")
add_case(t4_cpp_subnormal_coord t4_cpp "${RAD1}" t4_subnormal_coord "${SUCCESS}" EQ t4_subnormal_coord "${OUT}")
add_case(t4_cpp_leading_spaces t4_cpp "${RAD5}" t4_leading_spaces "${SUCCESS}" EQ t4_leading_spaces "${OUT}")
add_case(t4_cpp_exp_plus t4_cpp "${RAD400}" t4_exp_plus "${SUCCESS}" EQ t4_exp_plus "${OUT}")
add_case(t4_cpp_exp_upper t4_cpp "${RAD400}" t4_exp_upper "${SUCCESS}" EQ t4_exp_upper "${OUT}")
add_case(t4_cpp_exp_negative t4_cpp "${RAD1}" t4_exp_negative "${SUCCESS}" EQ t4_exp_negative "${OUT}")
add_case(t4_cpp_infinity_coord t4_cpp "${RAD1}" t4_infinity_coord "${DATA}" CONTAINS t4_infinity_coord "${ERR}")
add_case(t4_cpp_nan_payload_coord t4_cpp "${RAD1}" t4_nan_payload_coord "${DATA}" CONTAINS t4_nan_payload_coord "${ERR}")
add_case(t4_cpp_comma_coord t4_cpp "${RAD1}" t4_comma_coord "${DATA}" CONTAINS t4_comma_coord "${ERR}")
add_case(t4_cpp_dot_trailing_coord t4_cpp "${RAD8}" t4_dot_trailing_coord "${SUCCESS}" EQ t4_dot_trailing_coord "${OUT}")
add_case(t4_cpp_dot_leading_coord t4_cpp "${RAD5}" t4_dot_leading_coord "${SUCCESS}" EQ t4_dot_leading_coord "${OUT}")